# Generated by Django 4.1.2 on 2022-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('taskInfo', models.CharField(max_length=50)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
